# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: linter
on:
  push:
    branches: [ "main", "development"]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: golangci-lint
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=10m
          version: v1.53
          # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
          # install-mode: "goinstall"
